# Generated by Django 4.2.1 on 2023-05-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=255)),
                ('Images', models.ImageField(upload_to='products/images/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('add_cart', models.BooleanField(default=False)),
            ],
        ),
    ]
