# Generated by Django 4.2.1 on 2023-05-15 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='categories/images/')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'products_category',
            },
        ),
        migrations.AlterModelTable(
            name='products',
            table='products_product',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommers.category'),
        ),
    ]
