# Generated by Django 4.2.1 on 2023-05-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0002_category_alter_products_table_products_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
