# Generated by Django 4.2.1 on 2023-05-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0003_alter_products_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Images',
            new_name='images',
        ),
    ]
