# Generated by Django 4.2.1 on 2023-05-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0004_rename_images_products_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='images',
        ),
    ]
